protected/modules/admin/models/Station.php
<?php

/**
 * This is the model class for table "{{station}}".
 *
 * The followings are the available columns in table '{{station}}':
 * @property integer $id
 * @property integer $division_id
 * @property integer $district_id
 * @property string $name
 *
 * The followings are the available model relations:
 * @property PolicePrimaryinfo[] $policePrimaryinfos
 * @property PolicePrimaryinfo[] $policePrimaryinfos1
 * @property PolicePrimaryinfo[] $policePrimaryinfos2
 * @property District $division
 * @property District $district
 */
class Station extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{station}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			//array('division_id, district_id, name', 'required'),
			array('division_id, district_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, division_id, district_id, name', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'policePrimaryinfos' => array(self::HAS_MANY, 'PolicePrimaryinfo', 'division_id'),
			'policePrimaryinfos1' => array(self::HAS_MANY, 'PolicePrimaryinfo', 'district_id'),
			'policePrimaryinfos2' => array(self::HAS_MANY, 'PolicePrimaryinfo', 'station_id'),
			'division' => array(self::BELONGS_TO, 'District', 'division_id'),
			'district' => array(self::BELONGS_TO, 'District', 'district_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'division_id' => 'Division',
			'district_id' => 'District',
			'name' => 'Name',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('division_id',$this->division_id);
		$criteria->compare('district_id',$this->district_id);
		$criteria->compare('name',$this->name,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Station the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/modules/admin/controllers/StationController.php
<?php

class StationController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='main';

	
        public function actionIndex() {
            
            $model = new Station;
            
            $drop = CHtml::listData(Division::model()->findAll(), 'id', 'name');
            $drop2 = CHtml::listData(District::model()->findAll(), 'id', 'name');
            
            if(isset($_POST['Station'])){
                $model->attributes = $_POST['Station'];
                if($model->validate()){
                 $model->save();
                Yii::app()->user->setFlash('success','Data Saved Succesfully');    
                    
                }
            }
            
            $this->render('_form',array('model'=>$model,'drop'=>$drop,'drop2'=>$drop2));
        }
        
        
        public function actionGetdistrict() {
        $id = $_GET['category_id'];
        $districtList = District::model()->findAllByAttributes(array('division_id' => $id));
        $dropList = "";
        $dropList.="<option>Select District</option>";
        foreach ($districtList as $value) {
            $dropList.="<option value=" . $value['id'] . ">" . $value['name'] . "</option>";
        }

        $data = array(
            'success' => 'success',
            'dropList' => $dropList,
        );

        echo json_encode($data);
    }
        
        
        public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}
        
        
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Station']))
		{
			$model->attributes=$_POST['Station'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		Yii::app()->user->setFlash('danger','Data deleted Succesfully');
		$this->redirect(array('index'));
		
	}

	public function loadModel($id)
	{
		$model=Station::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Station $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='station-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/admin/views/station/_form.php
<?php
/* @var $this StationController */
/* @var $model Station */
/* @var $form CActiveForm */
?>

 <?php if (Yii::app()->user->hasFlash('success')) {
				foreach(Yii::app()->user->getFlashes() as $key => $message) {
				echo '<div font-Size: 20px; padding-top:20px", class="alert alert-success"' . $key . '"><button type="button" class="close" data-dismiss="alert">&times;</button><b><h4>'  . $message . "</h4></b></div>\n";
				}
				}
				?>
<?php if (Yii::app()->user->hasFlash('danger')) {
				foreach(Yii::app()->user->getFlashes() as $key => $message) {
				echo '<div font-Size: 20px; padding-top:20px", class="alert alert-danger"' . $key . '"><button type="button" class="close" data-dismiss="alert">&times;</button><b><h4>'  . $message . "</h4></b></div>\n";
				}
				}
				?>



<div class="row">
    
     <div class="col-md-6">
        <h4> <i class="fa fa-plus-circle"></i> Add Police Station </h4> <hr>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'division-form',
	'enableAjaxValidation'=>FALSE,
    'enableClientValidation'=>true,
    'clientOptions'=>array('validateOnSubmit'=>true, 'validateOnChange'=>true),
)); ?>
	

	

	<div class="form-group">
		<?php echo $form->labelEx($model,'division_id'); ?>
		<?php echo $form->dropDownList($model,'division_id',$drop,array('class'=>'form-control','style'=>'width: 122px')); ?>
	<?php echo $form->error($model,'division_id'); ?>
        </div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'district_id'); ?>
		<?php echo $form->dropDownList($model,'district_id',array('empty'=>'Select District'),array('class'=>'form-control','style'=>'width: 122px')); ?>
	<?php echo $form->error($model,'district_id'); ?>
        </div>

	<div class="form-group">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('class'=>'form-control','style'=>'width:150px')); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="form-group">
		<?php echo CHtml::submitButton('submit',array('class'=>'btn btn-success')); ?>
	</div>
        
        <?php $this->endWidget(); ?>
     </div>
    
    
    <div class="col-md-6">
        
        <h4><i class="fa fa-th-list"></i> Station List</h4><hr>
        
        <?php $data= Station::model()->findAll();   ?>
        
        <table id="example1" class="table table-bordered">
            <thead>
            <tr><td>SN</td><td>Station</td><td>Action</td></tr>
            </thead>
            <tbody>
            <?php $i=1;foreach($data as $value){ ?>
            <tr><td><?php echo $i; ?></td> <td><?php echo $value['name']; ?></td><td><a href="<?php echo Yii::app()->createUrl('station/delete',array('id'=>$value['id'])); ?>"  onclick="return confirm('Are you sure want to delete');"><i style="font-size: 15px;" class="fa fa-trash-o"></i></a></td></tr>
            <?php $i++;} ?>
            </tbody>
        </table>
        
    </div>



</div>

<script type="text/javascript">
                $(function() {
                    $("#example1").dataTable({ 
                        "iDisplayLength": 5,

            });
                    $('#example2').dataTable({
                        "bPaginate": true,
                        "bLengthChange": false,
                        "bFilter": false,
                        "bSort": true,
                        "bInfo": true,
                        "bAutoWidth": true
                    });
                });
        </script>
        
        
   <?php     
        $empurls = Yii::app()->createUrl('admin/station/getdistrict');
Yii::app()->getClientScript()->registerScript('empssscript', '
	$("#Station_division_id").change(function(){
		var category_id = $("#Station_division_id").val();
                
		$.ajax({
			url: "' . $empurls . '",
			data:{"category_id":category_id},
			beforeSend: function (){
                        $("#loader").show();    
                        },
			success: function (data) {
			var obj = jQuery.parseJSON(data);
			if(obj.success == "success"){
			$("#Station_district_id").html(obj.dropList);
			}
			  
			   
		}
	  });
	return false; 
	});  
  ', CClientScript::POS_READY);
?>